           -1.0       Qubit_at             15
           -1.0       Qubit_at             29
           -1.0       Qubit_at             33
           -1.0       Qubit_at             36
           -1.0       Qubit_at             40
           -1.0       Qubit_at             43
           -1.0       Qubit_at             47
           -1.0       Qubit_at             61
           -1.0       Qubit_at             64
           -1.0       Qubit_at             68
           -1.0       Qubit_at             71
           -1.0       Qubit_at             75
           -1.0       Qubit_at             78
           -1.0       Qubit_at             89
           -1.0       Qubit_at             92
           -1.0       Qubit_at             96
           -1.0       Qubit_at            103
            0.0      Measure_Z             33
            0.0      Measure_Z             40
            0.0      Measure_Z             47
            0.0      Measure_Z             61
            0.0      Measure_Z             68
            0.0      Measure_Z             75
            0.0      Measure_Z             89
            0.0      Measure_Z             96
            0.0      Measure_Z            103
