           -1.0       Qubit_at              1
           -1.0       Qubit_at              5
           -1.0       Qubit_at              8
           -1.0       Qubit_at             12
           -1.0       Qubit_at             15
           -1.0       Qubit_at             19
           -1.0       Qubit_at             22
           -1.0       Qubit_at             26
           -1.0       Qubit_at             29
           -1.0       Qubit_at             33
           -1.0       Qubit_at             36
           -1.0       Qubit_at             40
           -1.0       Qubit_at             43
           -1.0       Qubit_at             47
           -1.0       Qubit_at             50
           -1.0       Qubit_at             54
           -1.0       Qubit_at             57
           -1.0       Qubit_at             61
           -1.0       Qubit_at             64
           -1.0       Qubit_at             68
           -1.0       Qubit_at             71
           -1.0       Qubit_at             75
           -1.0       Qubit_at             78
           -1.0       Qubit_at             82
           -1.0       Qubit_at             85
           -1.0       Qubit_at             89
           -1.0       Qubit_at             92
           -1.0       Qubit_at             96
           -1.0       Qubit_at             99
           -1.0       Qubit_at            103
           -1.0       Qubit_at            106
           -1.0       Qubit_at            110
           -1.0       Qubit_at            113
           -1.0       Qubit_at            117
           -1.0       Qubit_at            120
           -1.0       Qubit_at            124
           -1.0       Qubit_at            127
           -1.0       Qubit_at            131
           -1.0       Qubit_at            134
           -1.0       Qubit_at            138
           -1.0       Qubit_at            141
           -1.0       Qubit_at            145
           -1.0       Qubit_at            148
           -1.0       Qubit_at            152
           -1.0       Qubit_at            155
           -1.0       Qubit_at            159
           -1.0       Qubit_at            162
           -1.0       Qubit_at            166
           -1.0       Qubit_at            169
           -1.0       Qubit_at            173
           -1.0       Qubit_at            176
           -1.0       Qubit_at            180
           -1.0       Qubit_at            183
           -1.0       Qubit_at            187
           -1.0       Qubit_at            190
           -1.0       Qubit_at            194
           -1.0       Qubit_at            197
           -1.0       Qubit_at            201
           -1.0       Qubit_at            204
           -1.0       Qubit_at            208
           -1.0       Qubit_at            211
           -1.0       Qubit_at            215
           -1.0       Qubit_at            218
           -1.0       Qubit_at            222
           -1.0       Qubit_at            225
           -1.0       Qubit_at            229
           -1.0       Qubit_at            232
           -1.0       Qubit_at            236
           -1.0       Qubit_at            239
           -1.0       Qubit_at            243
           -1.0       Qubit_at            246
           -1.0       Qubit_at            250
            0.0      Measure_Z             47
            0.0      Measure_Z             54
            0.0      Measure_Z             61
            0.0      Measure_Z             68
            0.0      Measure_Z             75
            0.0      Measure_Z             89
            0.0      Measure_Z             96
            0.0      Measure_Z            103
            0.0      Measure_Z            110
            0.0      Measure_Z            117
            0.0      Measure_Z            131
            0.0      Measure_Z            138
            0.0      Measure_Z            145
            0.0      Measure_Z            152
            0.0      Measure_Z            159
            0.0      Measure_Z            173
            0.0      Measure_Z            180
            0.0      Measure_Z            187
            0.0      Measure_Z            194
            0.0      Measure_Z            201
            0.0      Measure_Z            215
            0.0      Measure_Z            222
            0.0      Measure_Z            229
            0.0      Measure_Z            236
            0.0      Measure_Z            243
