dist: bionic
sudo: require
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - cmake-data
      - cmake
script:
    - cmake --version
    - $CC --version && $CXX --version
    - mkdir build && cd build
    - cmake ../
    - make
    - make test